name: CI (Java/Services)
on:
  push:
    branches: [ main, develop ]
  pull_request:
permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
      - uses: gradle/gradle-build-action@v3
        with:
          arguments: build -x test
      - name: Build Docker image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/services:sha-${{ github.sha }}
          docker build -t $IMAGE .
      - name: Login GHCR
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/services:sha-${{ github.sha }}
          docker push $IMAGE